import json
import random
import numpy as np
import torch
import logging
import time
import re
from contextlib import contextmanager
from typing import List, Dict, Union, Any

# Configure Logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

def set_seed(seed_value: int = 42):
    """Sets the seed for reproducibility across random, numpy, and torch."""
    random.seed(seed_value)
    np.random.seed(seed_value)
    torch.manual_seed(seed_value)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed_value)
    logger.info(f"Seed set to {seed_value}")

def load_json(filepath: str) -> Union[List, Dict]:
    """Safely loads a JSON file."""
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            return json.load(f)
    except Exception as e:
        logger.error(f"Error loading {filepath}: {e}")
        return []

def save_json(data: Any, filepath: str):
    """Safely saves data to a JSON file."""
    try:
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(data, f, indent=4)
    except Exception as e:
        logger.error(f"Error saving {filepath}: {e}")

@contextmanager
def timer(name: str):
    """Context manager to measure execution time of a block."""
    start_time = time.time()
    yield
    end_time = time.time()
    logger.info(f"[{name}] executed in {end_time - start_time:.4f} seconds")

def clean_sql_markdown(sql: str) -> str:
    """
    Cleans the SQL output generated by the LLM.
    Removes markdown backticks, 'sql' prefixes, and extracts the first query.
    """
    if not sql: return ""
    sql = str(sql).strip()
    
    # Remove markdown code blocks
    if sql.startswith("```sql"): sql = sql[6:]
    elif sql.startswith("```"): sql = sql[3:]
    if sql.endswith("```"): sql = sql[:-3]
    
    # Remove common prefixes
    if sql.lower().startswith("### solution:"): sql = sql[13:]
    if sql.lower().startswith("sql:"): sql = sql[4:]
    
    # Extract only the SQL part before any explanation
    sql_parts = re.split(r'Question:', sql, maxsplit=1, flags=re.IGNORECASE)
    sql = sql_parts[0].strip()
    
    # Take only the first statement
    sql = sql.split(';')[0].strip()
    return sql

def mask_question(question: str) -> str:
    """
    Masks named entities and values in the question using Heuristics/Regex.
    Goal: Transform "Show projects in France" -> "Show projects in [MASK]"
    to facilitate structural search.
    """
    # 1. Mask content inside quotes
    q = re.sub(r"['\"].*?['\"]", "[MASK]", question)
    
    # 2. Mask numbers
    q = re.sub(r"\b\d+\b", "[MASK]", q)
    
    # 3. Mask Capitalized words (likely Proper Nouns/Table Names), ignoring start of sentence
    def replace_proper_noun(match):
        # Avoid masking SQL keywords if they appear in upper case
        return "[MASK]" if match.group(0) != "SELECT" else match.group(0)

    # Regex: Find capitalized words not at the start of the string
    q = re.sub(r'(?<!^)(?<!\. )\b[A-Z][a-z0-9_]*\b', "[MASK]", q)
    return q